### ISSUE TITLE
What tools do you use on a daily basis? 

### ISSUE THREAD

**Issue by wesbos** [bwinton/ama#1]
and why do you choose them?

**Comment by bwinton** [comment]
The stuff that shows up in my dock is [Firefox](http://getfirefox.com/) (duh :wink:), [iTerm2](http://iterm2.com/), [LimeChat](http://limechat.net/mac/), [Atom](http://atom.io/) (and [Sublime Text](http://wesbos.com/sublime-text-book/)), and [GitX](https://github.com/rowanj/gitx/releases/) (rowanj fork).

The command line tools are [mercurial](http://mozilla-version-control-tools.readthedocs.org/en/latest/hgmozilla/index.html), [git](http://github.com/), [npm](http://npmjs.org/), [bower](http://bower.io/), and [jpm](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm).

I mostly try to choose things which are functional but also look nice.  I’m continually testing out new things, to see if they fit my workflow better, or what advantages they offer.  Sometimes I end up switching, sometimes not.  Heck, even after a couple of years using Sublime Text, I still pop open vim for some quick editing tasks.  :smile:
