### ISSUE TITLE
What do you think Firefox does better than the other browsers?

### ISSUE THREAD

**Issue by sindresorhus** [bwinton/ama#10]

**Comment by bwinton** [comment]
I think, despite Apple’s moves in this direction, Firefox is still the best browser for privacy and tracking protection.  Being not beholden to shareholders allows Mozilla to make a browser that has the users’ best interests at heart, and I hope that shows.  I’m also pretty excited to see which other companies Firefox will partner with, to bring the best of the web to people in way that’s both easy to use and open to extension by third-parties.

We’re also one of the [fastest browsers](http://arewefastyet.com/), but I don’t think people really care about that these days…  :wink:
