### ISSUE TITLE
What do you think of Servo?

### ISSUE THREAD

**Issue by sindresorhus** [bwinton/ama#12]
https://github.com/servo/servo

**Comment by bwinton** [comment]
I love it!  I don’t know any [Rust](https://github.com/rust-lang/rust), so I can’t tell you what the code quality is like, but I have a lot of trust in the people writing it.  :smile:

At the last FluentConf I saw @callahad do a demo, and it was impressively fast at rendering pages!  I can’t wait to see the integration of it and [browser.html](https://github.com/mozilla/browser.html).
