### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [bwinton/ama#15]

**Comment by bwinton** [comment]
That's nigh-impossible to answer.  There are [so many amazing ones](https://github.com/bwinton/whimsy/blob/gh-pages/thumbnail-gifs.txt)!

I *am* a fan of math and fractal related gifs:
![trippy…](http://24.media.tumblr.com/tumblr_m5ws79TQqT1r4231fo1_500.gif)
and gifs where people do amazing stunts:
![nice save](http://i.imgur.com/HQEdhaf.gif)
(even if they're in a video game)
![try this at home](http://gifmansion.com/GM/uploads/2013/06/Trackmania.gif)
 
But having said that, the gif I’ll probably use somewhere in Firefox soonest is
![spinner](http://i.imgur.com/Shhggfj.gif)
:smile:


ObNeilDegrasseTyson:
![the laws of physics](http://i.imgur.com/JjTg3u6.gif)
