### ISSUE TITLE
What is the best tool in your opinion to dry image files for the web?

### ISSUE THREAD

**Issue by alohavolha** [bwinton/ama#17]

**Comment by bwinton** [comment]
I'm not sure what you mean by "dry"…

If you mean compress, I've used [Pngcrush](http://pmt.sourceforge.net/pngcrush/) in the past for, uh, pngs, and MDN has a [great guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/SVG_Guidelines) for compressing SVGs, with links to more tools.

If you mean something else, please re-open this issue with a little more explanation, and I'll try to give you a better answer!  :smile:
