### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [bwinton/ama#6]

**Comment by bwinton** [comment]
Hey Arthur, thanks for the question!

My father was always buying the latest computers, so I got to play around with technology from a very early age.  Then when I was 10 or so, I went to a week-long summer camp where they taught us how to program (in BASIC, on Commodore PETs!)  I learned the basics there, but didn't really do much until my high school (grade 10) computer science course.  After I figured out I could make stuff just by thinking really hard, I was hooked.  :smile:

I hope that answered your question.  If you want more details, or to learn how I got into programming professionally, please re-open this issue!
