### ISSUE TITLE
What excites you most about the future of the web?

### ISSUE THREAD

**Issue by darcyclarke** [bwinton/ama#8]
As someone on the ground floor at a browser vendor you must get exposed to a lot of bleeding edge features, functionality and trends. What's coming down the pipeline that excites you most?

**Comment by bwinton** [comment]
Weirdly, I don’t see a lot of the web-facing stuff until it lands.  (It’s mostly done by people on the platform team, whereas I’m on the front-end team.)  And the stuff I do see is stuff that I can use (and have been using) _long_ before it’s widespread.  So, in that vein, I’ve recently been really enjoying using [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), and [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) (which I liked enough to write [a blog post](https://weblog.latte.ca/blake/tech/firefox/templates.html) about).  As features, they’re a little pedestrian, perhaps, but they make my code much nicer to read.
