### ISSUE TITLE
What do you do at Mozilla?

### ISSUE THREAD

**Issue by sindresorhus** [bwinton/ama#9]
Describe a normal day for you.

**Comment by bwinton** [comment]
I’m not entirely sure there is a *normal* day at Mozilla, but I’ll do my best.  :wink:

In the mornings I usually check email and irc to see if there’s anything urgent that’s cropped up while I’m asleep.  (Mostly there isn’t, but there’s usually a couple of things where I can provide extra information.)  After that I take a look at my list of tasks, pick one, and start working on it.  There are, of course, meetings to attend, and we get catered lunches, so the day is usually broken up a little.

In terms of what sort of tasks, they vary a lot depending on what projects I’m working on.  I’ve currently got a [prototype](https://github.com/bwinton/newtabsnippet) on the go which I need to add some [text and images](https://bugzilla.mozilla.org/show_bug.cgi?id=1181263) to.  I’m fixing and improving an internal dashboard which helps us figure out what features people are using, and talking to our User Advocacy team to get some custom reports run.  I installed Windows 10 on a Surface Pro, in preparation for some [upcoming polish work](https://firefox-ux.etherpad.mozilla.org/windows-10-papercuts).  (Reading back what I wrote, it seems that despite my claim that my tasks "vary a lot", they mostly seem to involve coding. :smile:)
